version: '3'
services:
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --secure-file-priv=""
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: motive
       MYSQL_USER: motive
       MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'


